---
- name: Wait 10 seconds before creating broker
  pause:
    seconds: 10

- name: Start Broker Interior 2 Master
  docker_container:
    name: Broker.M.I2
    image: "{{ image_broker }}"
    recreate: yes
    state: started
    published_ports: 8161:8161
    networks:
      - name: lab0
        ipv4_address: 192.168.8.10
        aliases:
          - brokeri2m
        links:
          - I2
    volumes:
      - "{{ inventory_dir }}/files/configs/broker-interior/master:/opt/broker1/etc"

- name: Start Broker Interior 2 Slave
  docker_container:
    name: Broker.S.I2
    image: "{{ image_broker }}"
    recreate: yes
    state: started
    published_ports: 8162:8162
    networks:
      - name: lab0
        ipv4_address: 192.168.8.20
        aliases:
          - brokeri2s
        links:
          - I2
          - brokeri2m
    volumes:
      - "{{inventory_dir}}/files/configs/broker-interior/slave:/opt/broker1/etc"

- name: Wait 30 seconds till Master and Slave handshake is complete
  pause:
    seconds: 30
