---
- name: Deploy Qpid Proton Python client cli-proton-python
  docker_container:
    name: cli-proton-python
    image: rhmessagingqe/cli-proton-python
    state: started
    recreate: yes
    command: "sh"
    interactive: yes
    networks:
      - name: lab0
        aliases:
          - cli-proton-python
        links:
          - Broker.M.I2
          - Broker.S.I2
          - Broker.M.E3
          - Broker.S.E3
          - Router.I1
          - Router.I2
          - Router.I3
          - Router.E1
          - Router.E2
          - Router.E3
    volumes:
      - "{{ inventory_dir }}/files/clients-data/cli-proton-python:/var/lib/cli-proton-python"
      - "{{ inventory_dir }}/files/clients-data/msgs:/var/lib/cli-proton-python/msgs"

- name: Deploy RHEA NodeJS client cli-rhea
  docker_container:
    name: cli-rhea
    image: rhmessagingqe/cli-rhea:centos7
    state: started
    recreate: yes
    command: "sh"
    interactive: yes
    networks:
      - name: lab0
        aliases:
          - cli-rhea
        links:
          - Broker.M.I2
          - Broker.S.I2
          - Broker.M.E3
          - Broker.S.E3
          - Router.I1
          - Router.I2
          - Router.I3
          - Router.E1
          - Router.E2
          - Router.E3
    volumes:
      - "{{ inventory_dir }}/files/clients-data/cli-rhea:/var/lib/cli-rhea"
      - "{{ inventory_dir }}/files/clients-data/msgs:/var/lib/cli-rhea/msgs"

- name: Deploy clients cli-java
  docker_container:
    name: cli-java
    image: rhmessagingqe/cli-java
    state: started
    recreate: yes
    command: "sh"
    interactive: yes
    networks:
      - name: lab0
        aliases:
          - cli-java
        links:
          - Broker.M.I2
          - Broker.S.I2
          - Broker.M.E3
          - Broker.S.E3
          - Router.I1
          - Router.I2
          - Router.I3
          - Router.E1
          - Router.E2
          - Router.E3
    volumes:
      - "{{ inventory_dir }}/files/clients-data/cli-java:/var/lib/cli-java"
      - "{{ inventory_dir }}/files/clients-data/msgs:/var/lib/cli-java/msgs"
